name: Build Project

on:
  push:
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: '1.0.0'
        type: string
        description: 'Release version (e.g., 1.0.0)'
permissions:
  packages: write

jobs:
  mvn-build:
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode package"
      upload-artifact: true
      artifact-id: ${{ github.event.repository.name }}
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}
  perform-version:
    runs-on: ubuntu-latest
    needs: mvn-build
    outputs:
      metadata: "${{ steps.metadata.outputs.result }}"
      tags: "${{ steps.prepare_tags.outputs.tags }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create name
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@main
        id: metadata

      - name: Prepare tags
        id: prepare_tags
        run: |
          BASE_TAG="${{ steps.metadata.outputs.result }}"
          EXTRA_TAG="${{ github.event.inputs.tags }}"
          if [ -n "$EXTRA_TAG" ]; then
            TAGS="${BASE_TAG}, ${EXTRA_TAG}"
          else
            TAGS="${BASE_TAG}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Summary step
        run: |
          echo "**Metadata:** ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY
          echo "**Tags:** ${{ steps.prepare_tags.outputs.tags }}" >> $GITHUB_STEP_SUMMARY

  docker-build:
    uses: netcracker/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    needs: perform-version
    with:
      ref: ${{ github.event.ref }}
      artifact-id: ${{ github.event.repository.name }}
      dry-run: false
      download-artifact: true
      tags: ${{ needs.perform-version.outputs.tags }}
